# Generated by Django 3.1.7 on 2021-03-01 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iletisim', '0010_remove_i̇nfo_campanyname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='İnfo',
        ),
    ]
