# Generated by Django 3.1.7 on 2021-03-01 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iletisim', '0011_delete_i̇nfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='iletişim tarihi'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(verbose_name='mesaj'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=30, verbose_name='isim'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=25, null=True, verbose_name='konu'),
        ),
    ]
